### ISSUE TITLE
cloudstack_system_template fail on Chef14

### ISSUE THREAD

**Issue by pdion891** [cloudops/cookbook_cloudstack#20]
```
         * cloudstack_system_template[xenserver] action create

           ================================================================================
           Error executing action `create` on resource 'cloudstack_system_template[xenserver]'
           ================================================================================

           NameError
           ---------
           uninitialized constant Chef::Resource::CloudstackSystemTemplate

           Cookbook Trace:
           ---------------
           /tmp/kitchen/cache/cookbooks/cloudstack/providers/system_template.rb:41:in `load_current_resource'

           Resource Declaration:
           ---------------------
           # In /tmp/kitchen/cache/cookbooks/cloudstack_wrapper/recipes/management_server.rb

            44: cloudstack_system_template 'xenserver' do
            45:   nfs_path    node['cloudstack']['secondary']['path']
            46:   nfs_server  node['cloudstack']['secondary']['host']
            47:   url         node['cloudstack']['systemvm']['xenserver']
            48:   db_user     node['cloudstack']['db']['user']
            49:   db_password node['cloudstack']['db']['password']
            50:   db_host     node['cloudstack']['db']['host']
            51:   action :create
            52: end
            53:

           Compiled Resource:
           ------------------
           # Declared in /tmp/kitchen/cache/cookbooks/cloudstack_wrapper/recipes/management_server.rb:44:in `from_file'

           cloudstack_system_template("xenserver") do
             action [:create]
             default_guard_interpreter :default
             declared_type :cloudstack_system_template
             cookbook_name "cloudstack_wrapper"
             recipe_name "management_server"
             nfs_path "/data/secondary"
             nfs_server "10.178.52.118"
             url "<REMOVED>"
             db_user "cloud"
             db_password "password"
             db_host "127.0.0.1"
             hypervisor "xenserver"
           end

           System Info:
           ------------
           chef_version=14.6.47
           platform=centos
           platform_version=7.6.1810
           ruby=ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-linux]
           program_name=/opt/chef/bin/chef-client
           executable=/opt/chef/bin/chef-client

       Running handlers:
       [2018-12-28T09:09:35-05:00] ERROR: Running exception handlers
       Running handlers complete
       [2018-12-28T09:09:35-05:00] ERROR: Exception handlers complete
       Chef Client failed. 10 resources updated in 07 seconds
       [2018-12-28T09:09:35-05:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
       [2018-12-28T09:09:35-05:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
       [2018-12-28T09:09:35-05:00] FATAL: NameError: cloudstack_system_template[xenserver] (cloudstack_wrapper::management_server line 44) had an error: NameError: uninitialized constant Chef::Resource::CloudstackSystemTemplate
```

**Comment by khos2ow** [comment]
This is fixed in #18
